spring:
  application:
    name: estoque-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://positivo-server:5432/exemplo_estoque
    username: postgres
    password: postgres@123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /estoque-api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO
